name: M3O
company_name: Micro Services, Inc
description: The open source public cloud platform
meta_description: "M3O is an open source public cloud platform. An AWS alternative for the next generation of developers."
markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
gems: [jekyll-paginate, redcarpet, jekyll-gist, pygments.rb]
future: true
plugins: [jekyll-paginate, redcarpet, jekyll-gist, pygments.rb]
# Details for the RSS feed generator
url:            'https://blog.m3o.com/'
author:         'Asim Aslam'
author_url:     'https://github.com/asim'
twitter_url:	'https://twitter.com/m3oservices'
paginate_path: "/page:num/"
google_analytics: UA-70478210-4
sidebars:
- home_sidebar
defaults:
  -
    scope:
      path: "docs"
      type: "pages"
    values:
      layout: "docs/page"
      comments: true
      search: true
      sidebar: home_sidebar
      lang: en

output: web
topnav_title: M3O
site_title: M3O
exclude: [main.go]
